[package]
name = "hp"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "hp"
crate-type = ["cdylib"]

[dependencies]
openssl-sys = { version = "*", features = ["vendored"] }
pyo3 = { version = ">= 0.28.2", features = ["extension-module"] }
rust-htslib = "*"
rayon = "*"
tokio = "*"
itertools = "*"
bigtools = "*"
flate2 = "*"
tempfile = "*"
ndarray = "*"
ndarray-npy = "*"
