trigger:
  branches:
    include:
    - '*'
pr:
  branches:
    include:
    - '*'
jobs:
- job: install_deeptools_run_tests
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - bash: conda create -n foo -q --yes -c conda-forge -c bioconda python=$(python.version) numpy scipy matplotlib==3.1.1 nose flake8 plotly pysam pyBigWig py2bit deeptoolsintervals
    displayName: Installing dependencies
  - bash: |
      source activate foo
      python -m pip install . --no-deps --ignore-installed -vvv
    displayName: Installing deeptools
  - bash: |
      source activate foo
      flake8 . --exclude=.venv,.build,build --ignore=E501,F403,E402,F999,F405,E722,W504,W605
    displayName: flake8
  - bash: |
      source activate foo
      nosetests --with-doctest -sv deeptools
    displayName: Test deepTools
