steps:
- bash: conda create -n foo -q --yes -c conda-forge -c bioconda python=$(python.version) numpy scipy matplotlib==2.1.2 nose flake8 plotly==2.0.12 pysam pyBigWig py2bit deeptoolsintervals cython
  displayName: Installing dependencies
- bash: |
    source activate foo
    python setup.py install
  displayName: Installing deeptools
- bash: |
    source activate foo
    flake8 . --exclude=.venv,.build,build --ignore=E501,F403,E402,F999,F405,E722,W504,W605
  displayName: flake8
- bash: |
    source activate foo
    nosetests --with-doctest -sv deeptools
  displayName: Test deepTools
