name: Build Python Wheels

on: [push, pull_request, workflow_dispatch]

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64, i686]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          architecture: x64
          cache: 'pip'
      - name: Build wheels
        uses: PyO3/maturin-action@v1
        env:
          RUST_BACKTRACE: "1"
        with:
          target: ${{ matrix.target }}
          # sccache: 'true'
          args: --release --out dist --find-interpreter
          manylinux: "auto"
          # Following is a workaround taken from:
          # https://github.com/Intreecom/scyllapy/blob/develop/.github/workflows/release.yaml
          before-script-linux: |
            set -ex
            # Print the current distribution information
            echo "System Information:" && uname -a
            if command -v lsb_release &> /dev/null; then
                lsb_release -a
            elif [ -f /etc/os-release ]; then
                cat /etc/os-release
            elif [ -f /etc/redhat-release ]; then
                cat /etc/redhat-release
            elif [ -f /etc/debian_version ]; then
                echo "Debian Version: $(cat /etc/debian_version)"
            else
                echo "Distribution information not found."
            fi
            if command -v yum &> /dev/null; then
                yum update -y
                yum-config-manager --add-repo https://mirrors.fedoraproject.org/metalink?repo=epel-7&arch=${{ matrix.target }}
                yum install -y perl-devel curl openssl openssl-libs openssl-devel pkgconfig libatomic clang-devel xz-devel
                if [[ ! -d "/usr/lib64" ]]; then
                    ln -s /usr/lib/libatomic.so.1 /usr/lib/libatomic.so
                fi
            else
                apt update -y && apt-get install -y perl-modules curl libssl-dev openssl pkg-config libclang-dev liblzma-dev
            fi
            curl -L https://cpanmin.us | perl - --sudo App::cpanminus
            cpanm ExtUtils::Manifest && cpanm YAML IPC::Cmd
            export OPENSSL_LIB_DIR=$(pkg-config --variable=libdir openssl)
            export OPENSSL_INCLUDE_DIR=$(pkg-config --variable=includedir openssl)
            if [ -z "$OPENSSL_LIB_DIR" ] || [ -z "$OPENSSL_INCLUDE_DIR" ]; then
                echo "OpenSSL development files are not installed or pkg-config is not configured correctly."
                exit 1
            fi
            export OPENSSL_DIR="$OPENSSL_LIB_DIR/ssl"
            export OPENSSL_NO_VENDOR=1

