name: tests_planemo
on: [push, pull_request, workflow_dispatch]

permissions:
    contents: read

env:
    GALAXY_BRANCH: release_26.0

defaults:
    run:
        shell: bash -l {0}

jobs:
    planemo_test:
        name: Planemo test
        runs-on: ubuntu-latest
        strategy:
            matrix:
                chunk: [1, 2, 3]
        steps:
            - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
              with:
                persist-credentials: false
            - uses: conda-incubator/setup-miniconda@8ee1f361103df19b6f8c8655fd3967a8ecb162d5 # v4.0.1
              with:
                  miniconda-version: "latest"
                  auto-activate-base: true
                  python-version: "3.12"
            - name: get samtools
              run: |
                  conda install -c conda-forge -c bioconda samtools
            - name: pip install
              run: |
                  pip install .[actions]
            - name: planemo
              run: |
                  ./.planemo.sh ${{ matrix.chunk }} ${{ env.GALAXY_BRANCH }}
            - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
              with:
                  name: "Tool test output ${{ matrix.chunk }}"
                  path: upload
    planemo_combine_outputs:
        name: Combine chunked test results
        needs: planemo_test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
              with:
                  path: artifacts
            - name: Combine outputs
              uses: galaxyproject/planemo-ci-action@823fb30673dde862fcf88fd267c369920675fb53 # v1.0.29
              id: combine
              with:
                  mode: combine
                  html-report: true
            - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
              with:
                  name: "All tool test results"
                  path: upload
            - name: Check outputs
              uses: galaxyproject/planemo-ci-action@823fb30673dde862fcf88fd267c369920675fb53 # v1.0.29
              id: check
              with:
                  mode: check
