name: tests_planemo
on: [push, pull_request, workflow_dispatch]

env:
    GALAXY_BRANCH: release_26.0

defaults:
    run:
        shell: bash -l {0}

jobs:
    planemo_test:
        name: Planemo test
        runs-on: ubuntu-latest
        strategy:
            matrix:
                chunk: [1, 2, 3]
        steps:
            - uses: actions/checkout@v4
            - uses: conda-incubator/setup-miniconda@v3
              with:
                  miniconda-version: "latest"
                  auto-activate-base: true
                  python-version: "3.12"
            - name: get samtools
              run: |
                  conda install -c conda-forge -c bioconda samtools
            - name: pip install
              run: |
                  pip install .[actions]
            - name: planemo
              run: |
                  ./.planemo.sh ${{ matrix.chunk }} ${{ env.GALAXY_BRANCH }}
            - uses: actions/upload-artifact@v4
              with:
                  name: "Tool test output ${{ matrix.chunk }}"
                  path: upload
    planemo_combine_outputs:
        name: Combine chunked test results
        needs: planemo_test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/download-artifact@v4
              with:
                  path: artifacts
            - name: Combine outputs
              uses: galaxyproject/planemo-ci-action@v1
              id: combine
              with:
                  mode: combine
                  html-report: true
            - uses: actions/upload-artifact@v4
              with:
                  name: "All tool test results"
                  path: upload
            - name: Check outputs
              uses: galaxyproject/planemo-ci-action@v1
              id: check
              with:
                  mode: check
